INSERT INTO TYPE_ACTIVITY (name) VALUES ('Rodaje normal');
INSERT INTO TYPE_ACTIVITY (name) VALUES ('Caminata');
INSERT INTO TYPE_ACTIVITY (name) VALUES ('Series');
INSERT INTO TYPE_ACTIVITY (name) VALUES ('Fartlek');
INSERT INTO TYPE_ACTIVITY (name) VALUES ('Rodaje suave');